# Permalinks
permalink:           pretty

# Setup
title:               Deep Learning 
tagline:             MENG ZHOU
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Zhou Meng 
  url:               http://zhou503m.github.io
  email:             594587207@qq.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/zhou503m/zhou503m.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
